### DISCUSSION TITLE
Multiple tunnel ?

### DISCUSSION THREAD

**Discussion by Yuss9** [amalshaji/portr#31] [Q&A] [answered]
Hey 👋 I would like to know if it is possible to use portr and start multiple tunnel on different port at the same time and on the same account ? For example, sometimes i need to start tunnel on port 3000 for the front and on port 5555 for database with prisma studio 🚀 

Have a good day 👋

**Comment by amalshaji** [comment, marked as answer]
Yes, it is possible by adding them as services in the portr config file

```bash
portr config edit
```

This should open your default config file. Then add your required ports as services

```yaml
server_url: example.com
ssh_url: example.com:2222
secret_key: <secret-key>
tunnels:
  - name: frontend
    subdomain: my-frontend
    port: 3000
  - name: prisma-studio
    subdomain: my-prisma-studio
    port: 5555
```

This assumes both the services are HTTP. If you want to run TCP, add TCP type at the end

```yaml
    subdomain: my-prisma-studio
    port: 5555
    type: tcp
```

Then start both services using `portr start frontend prisma-studio`
