### ISSUE TITLE
Enhancement Request: Secure SSH Authorization in Docker Compose for Improved Instance Security

### ISSUE THREAD

**Issue by 3h04m1** [amalshaji/portr#40]
**Is your feature request related to a problem? Please describe.**
Ensuring secure SSH authorization is paramount, especially for users concurrently hosting multiple projects on a single server. The current lack of SSH security poses a significant vulnerability that needs addressing promptly.

**Describe the solution you'd like**
Enhancing security within the Docker Compose file by enabling users to specify the path to their public key or password for SSH authorization would be a significant improvement. This feature would empower users to fortify their instances against potential security breaches effectively.

**Describe alternatives you've considered**
While less preferable due to potential user inconvenience, an alternative method could involve clients providing passwords or certificates during authorization. However, this approach might sacrifice some user-friendliness for increased security measures.

**Comment by amalshaji** [comment]
We are already doing auth using the secret key https://github.com/amalshaji/portr/blob/1afaa6775ac6cf20db670d98c8eb97a5926de609/tunnel/internal/server/ssh/sshd.go#L126-L128

**Comment by 3h04m1** [comment]
> We are already doing auth using the secret key
> 
> https://github.com/amalshaji/portr/blob/1afaa6775ac6cf20db670d98c8eb97a5926de609/tunnel/internal/server/ssh/sshd.go#L126-L128

Maybe I misunderstood something, I am getting this error:` ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain`

when setting up the server I completed all the required fields in .env file:
```
PORTR_SERVER_URL=example.com
PORTR_SSH_URL=example.com:2222
```

here is no field for the ssh password or some public key, my ssh auth is based on password and I thought that maybe there is an issue with authentication

**Comment by amalshaji** [comment]
Are you running the server locally? Can you provide more information about your setup? And the steps you ran that lead to this error?

**Comment by 3h04m1** [comment]
> Are you running the server locally? Can you provide more information about your setup? And the steps you ran that lead to this error?

Docker Compose file:
```
services:
  admin:
    image: amalshaji/portr-admin:0.0.10-beta
    env_file: .env
    restart: unless-stopped
    ports:
      - "6300:8000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  tunnel:

    image: amalshaji/portr-tunnel:0.0.10-beta
    command: ["start"]
    ports:
      - "6301:8001"
    env_file: .env
    restart: unless-stopped
    depends_on:
      admin:
        condition: service_healthy
```

.env file:
```
PORTR_ADMIN_GITHUB_CLIENT_ID=******
PORTR_ADMIN_GITHUB_CLIENT_SECRET=******

PORTR_DOMAIN=portr.******
PORTR_DB_URL=postgres://portr:******@******:5432/portr

PORTR_SERVER_URL=******
PORTR_SSH_URL=******:2222

PORTR_ADMIN_ENCRYPTION_KEY=******
```

I am using a manged postgress, and for proxy nginx

```
